import Header from "@/component/header/Header";
import Sidebar from "@/component/sideBar/Sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Technolab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Container principal */}
        <div className="flex flex-col h-screen">
          <Header />
          <div className="w-[400px] flex flex-row h-full">
            <div>
              <Sidebar />
            </div>
            <main className="w-full bg-slate-100 p-4">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
